### ISSUE TITLE
Get apps upgraded to 0.10.0-beta asap

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#626]
* [x] My favorite drinks
* [x] Webmarks
* [x] Sharesome
* [x] Litewrite (litewrite/litewrite#211)
* [x] Grouptabs (xMartin/grouptabs#67)
* [x] Ghost (vcuculo/ghost-unhosted-webrtc#13)
* [x] Dogfeed (silverbucket/dogfeed#54)
* [x] Laverna (Laverna/laverna#31)
* [ ] remotestorage-browser
* [x] mcnotes (mc96107/mcnotes#1)
* [ ] Alir (clochix/alir#8)
* [x] Moka (sebn/moka#13)
* [ ] vidmarks (silverbucket/vidmarks#6)
* [ ] unhosted-time-tracker (shybyte/unhosted-time-tracker#9)
* [ ] Remote Tiddly Wiki

**Comment by skddc** [comment]
Lol for this not having been closed yet. :)
